name: Rodar Leitor de Contrato

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install -r leitor_contrato/requirements.txt

    - name: Executar main.py
      run: python leitor_contrato/main.py
